# Generated by Django 4.2.3 on 2023-07-22 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.CharField(max_length=16, unique=True)),
                ('expiration_date', models.CharField(max_length=7)),
                ('cvv', models.CharField(max_length=3)),
                ('issue_date', models.DateField()),
                ('card_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_frozen', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
